### ISSUE TITLE
Why both GLFW aand GLUT being used in libigl-example-project

### ISSUE THREAD

**Issue by Namdhari** [libigl/libigl-example-project#1]
Why both GLFW aand GLUT being used in libigl-example-project ?
Referring libigl-example-project/CMakeLists.txt

find_package(GLFWH REQUIRED)
include_directories( ${GLFW_INCLUDE_DIR})
find_package(GLUT REQUIRED)

Is it a mistake or deliberately done ?

**Comment by alecjacobson** [comment]
Yup, that was a mistake. I just pushed a fix affdffaf7128b33bf7ab3c48bb4af2acf86553a3.
