### ISSUE TITLE
Use libigl.cmake

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl-example-project#10]
It doesn't seem that this example project is actually using the new cmake paradigm that @jdumas added.

**Comment by jdumas** [comment]
But it is, no? The `FindLIBIGL.cmake` includes `libigl.cmake` on [L36](https://github.com/libigl/libigl-example-project/blob/8d3c17e15ee146a0436e64df5549d28569fe982c/cmake/FindLIBIGL.cmake#L36). And the main [`CMakeLists.txt`](https://github.com/libigl/libigl-example-project/blob/8d3c17e15ee146a0436e64df5549d28569fe982c/CMakeLists.txt#L31) is linking against `igl::core` and `igl::viewer`.

**Comment by alecjacobson** [comment]
I think you're right. I might have mangled my cmake setup. Should we delete the old `shared/cmake/CMakeLists.txt`. Is this being used somehow?

**Comment by jdumas** [comment]
It should not be used anymore. I think it is nice to leave it for a while to smooth the transition for those who are updating libigl ... but it's up to you to decide how long you want to keep it =)

**Comment by alecjacobson** [comment]
I think it's actually make it less smooth and pro-longing the transition since it can be accidentally invoked.

@danielepanozzo  shall we remove it?

**Comment by danielepanozzo** [comment]
It is not used anywhere, we left it there just for backward compatibility. It has been around already for a few months, I think it is ok to remove it now.

**Comment by zjulion** [comment]
set libigl_dir (or sth like that) in you cmakelists.txt
