### ISSUE TITLE
Project cannot find <#include <imgui/imgui.h>

### ISSUE THREAD

**Issue by avaxman** [libigl/libigl-example-project#12]
I tried to create an example using the new imgui by copying the main.cpp file from libigl/tutorial106_ViewerMenu. Aside from necessary adaptation, it doesn't seem to recognize imgui, giving the following error:

/Users/amirvaxman/libigl/include/igl/opengl/glfw/imgui/ImGuiMenu.cpp:11:10: 'imgui/imgui.h' file not found

Is there some cmake flag in the example project that I should light for this to happen? I just tried replacing the contents of the main.cpp with the one of tutorial 106 and compile.

**Comment by danielepanozzo** [comment]
You probably forgot to add *igl::opengl_glfw_imgui* to  ```target_link_libraries``` in CMakeLists.txt

**Comment by avaxman** [comment]
Yes that did the trick for this specific problem. Thanks! (perhaps worth mentioning in text?)

**Comment by r03ert0** [comment]
This issue saved my day!! I was trying to compile example 608 (locally injective maps), which required to add igl::lim to the targets. It's maybe a good idea to add that to the text as @avaxman suggested...

**Comment by ShaYito** [comment]
> _igl::opengl_glfw_imgui_

After I did this, there are errors like:
```
CMake Error at CMakeLists.txt:94 (add_executable):
  Target "ela" links to target "igl::opengl_glfw_imgui" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:94 (add_executable):
  Target "ela" links to target "igl::opengl_glfw_imgui" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:94 (add_executable):
  Target "ela" links to target "igl::opengl_glfw_imgui" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:94 (add_executable):
  Target "ela" links to target "igl::opengl_glfw_imgui" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
Can anybody help me?

**Comment by khan-codes** [comment]
@ShaYito Add `option(LIBIGL_IMGUI "Build target igl::imgui" ON)` in the CMakeLists.txt before target_link_libraries().
