### ISSUE TITLE
Continuous Integration testing

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl-example-project#20]
[to-do:] We should have continuous integration for this example project.

**Comment by BruegelN** [comment]
Is this still up to date?
I'd assume that switching over to Github Actions for libigl makes PR #21 (Travis CI + AppVeyor) obsolete?! If so feel free to just close it :smile:  
I've started to add Github Actions: https://github.com/BruegelN/libigl-example-project/tree/github-actions
It might be nice to have an external rigger (push/merge on libigl repo) to start builds on this repo which could be achieved by `repository_dispatch`: https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
Maybe @jdumas has further suggestion?

**Comment by jdumas** [comment]
It's a good idea to use external hooks to trigger builds here. Worst case we can always have a nightly build for this example project as well.

**Comment by jdumas** [comment]
Fixed by #31
