### ISSUE TITLE
Building libigl-example-project nightmare

### ISSUE THREAD

**Issue by pauljurczak** [libigl/libigl-example-project#25]
I've installed `libigl` on Ubuntu 18.04.3 as directed by tutorial. I was able to use it in a project with `geometry-central` and `polyscope` with no problems. Now I'm trying to build just a `libigl-example-project` and it doesn't work. I noticed that the build process seems to require `LIBIGL_` environment variables to be set, but none is after `libigl` installation. 

The first attempt at build produces:
```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  libigl not found --- You can download it using:
```

After adding `set(LIBIGL_INCLUDE_DIR /home/paul/libraries/libigl)` to `CMakeLists.txt`, I'm getting:
```
CMake Error at cmake/FindLIBIGL.cmake:34 (include):
  include could not find load file:
    libigl
```
There is no `libigl` anywhere in the file system. What file is it? What environment variables are needed for a successful build? I'm a beginner user of `cmake`, but if I knew what paths it is searching for with `find_path`, maybe I could just set them manually.

I'm not sure what  `LIBIGL_INCLUDE_DIR - **the** LIBIGL include directory` means. Is setting it to the root of `libigl` correct, as in `set(LIBIGL_INCLUDE_DIR /home/paul/libraries/libigl)`?

**Comment by jdumas** [comment]
Hi. I'm sorry you're having trouble setting this up. Please let us know how we can improve our documentation to make it easier to get started with this example project (e.g. which page of the doc did you consult? What steps did you try, etc?).

Regarding your problem at hand, the first error message (`libigl not found --- You can download it using`) will tell you to download/clone the libigl repository in the parent folder to the `libigl-example-project/` folder, so you will have the following directory structure:
```
<workspace>
├── libigl
└── libigl-example-folder
```

If your files are organized as such, then `FindLIBIGL.cmake` will find libigl and use it. Otherwise, you can specify the path to the `libigl/` folder using either the environment variable:
```
mkdir build/ && cd build/
LIBIGL_DIR=<path_to_libigl> cmake ..
```

Or by setting the *CMake* variable `LIBIGL_DIR` as such:
```
mkdir build/ && cd build/
cmake -DLIBIGL_DIR=<path_to_libigl> ..
```
If you're under Windows the second option might be a bit easier to do.

**Comment by pauljurczak** [comment]
Thank you for quick response. I'm building on Linux. I tried both suggestions with the same result as before:

1. I changed directory structure to:
```
/home/paul/Downloads/
├── libigl
└── libigl-example-folder
```
still keeping the original at `/home/paul/libraries/libigl/`

2. I added `set(LIBIGL_DIR /home/paul/libraries/libigl/)` or `set(LIBIGL_DIR /home/paul/libraries/)` to my `CMakeList.txt`:
```
cmake_minimum_required(VERSION 3.1)
project(example)

set(LIBIGL_INCLUDE_DIR /home/paul/libraries/libigl/)
set(LIBIGL_DIR /home/paul/libraries/libigl/)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

# libigl
option(LIBIGL_WITH_OPENGL            "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW       "Use GLFW"           ON)

find_package(LIBIGL REQUIRED QUIET)

# Add your project files
file(GLOB SRCFILES *.cpp)
add_executable(${PROJECT_NAME}_bin ${SRCFILES})
target_link_libraries(${PROJECT_NAME}_bin igl::core igl::opengl_glfw)
```

**Comment by jdumas** [comment]
Which version of libigl are you using? The libigl repository should have a file `libigl/cmake/libigl.cmake`. Do not set `LIBIGL_INCLUDE_DIR` manually.

**Comment by pauljurczak** [comment]
Removing `set(LIBIGL_INCLUDE_DIR /home/paul/libraries/libigl/)` solved the problem, thank you. I'm using a version cloned from github a week ago. 

I had a bit of a problem putting `libigl` inside a large project, but it's all good now. The key was to copy `cmake/FindLIBIGL.make` from `libigl-example-project-master` to sources directory of the new project.

Thank you for your help. I was getting ready to just write what I need in OpenGL.

**Comment by jdumas** [comment]
Cool. Out of curiosity, which page of the website were you reading when you were trying to configure this?

**Comment by pauljurczak** [comment]
I've built `libigl` following https://libigl.github.io/tutorial/; `libigl-example-project-master` reading https://github.com/libigl/libigl-example-project/blob/master/README.md

I'm not sure, if this is helpful, but I started with experimenting with `polyscope`, which has a viewer for `libigl` and their build process (https://github.com/nmwsharp/polyscope) masked all the difficulties I just had. I run into them only after removing `geometry-central` and `polyscope`. Also, my knowledge of `cmake` is very minimal.

**Comment by jdumas** [comment]
Well yes, polyscope has an example project repository which is configured to use libigl. This is nice, but as you said the moment you want to integrate libigl into another project of yours, you will have to fiddle with CMake yourself. I don't think there is anyway around it. Also, I am not a fan of submodules (which is how the polyscope example project incorporate the libigl dependency), as they have their own set of drawbacks.
