### ISSUE TITLE
Glew not found while building

### ISSUE THREAD

**Issue by Namdhari** [libigl/libigl-example-project#3]
**Environment** : Windows 10, VS 2013
**Error** : glew not found during compilation

**Comment by alecjacobson** [comment]
I added the GLEW lines from the libigl/tutorial/CMakeLists.shared
in general, if you can get the tutorial to build we should be able to get
this project to build by mirroring the CMake settings there. I encourage
trying to do this and then submitting a pull request with changes (I don't
have a windows machine to test on right now).

**Comment by Namdhari** [comment]
Yes, I was able to build the Tutorial.
However there was an error form nonogui due to snprintf. Which I resolved by adding following.
#ifdef WIN32
#define snprintf _snprintf
#endif


Further I am able to build libigl-example-project, after adding the GLEW changes. I am going to send you a pull request.

**Comment by alecjacobson** [comment]
Where did you have to add the snsprintf thing? I don't think that should be
necessary.

**Comment by Namdhari** [comment]
Changes done in textbox.h and layout.h

**Comment by alecjacobson** [comment]
Hmm I recommend trying to resolve this as an issue on the nanogui page.
