### ISSUE TITLE
building with 2017 versions

### ISSUE THREAD

**Issue by Philius** [libigl/libigl-example-project#32]
I've got a project that worked in 2017 but doesn't work now.
Rewriting it is obvoiusly the preferred solution but in the short term it would seem possible to clone the repos and reset to the right commits.
```
libigl:
git reset --hard 1630b0b480c2c0099b3accab8c83b88ca9dd29d9

nanogui:
git reset --hard 0a818da9bdebafb7d600f5bc4d64eed938defce4

glfw: ?

libigl example project:
git reset --hard 8d3c17e15ee146a0436e64df5549d28569fe982c
```
I found these through trial and error, more git branches would have helped.
The
```
git clone --recursive https://github.com/libigl/libigl.git
```
command won't do what's needed as there is no .gitmodules file, so I cloned nanogui into the `external` folder I created in libigl.
So far, so good.

I'm stumped at the last hurdle:
```
CMake Error at CMakeLists.txt:30 (add_executable):
  Target "example_bin" links to target "igl::viewer" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```
I can't find anywhere that creates this target.

**Comment by jdumas** [comment]
2017 is like, ages ago. In 2018 we rewrote libigl's git history to free up space taken by binary data. You can read more about this on [this page](https://libigl.github.io/rewritten-history/). If you know which commit SHA1 worked for you with the old repo, you can use the old repo [libigl-legacy](https://github.com/libigl/libigl-legacy) with the same SHA1.

**Comment by Philius** [comment]
> 2017 is like, ages ago. In 2018 we rewrote libigl's git history to free up space taken by binary data. You can read more about this on [this page](https://libigl.github.io/rewritten-history/). If you know which commit SHA1 worked for you with the old repo, you can use the old repo [libigl-legacy](https://github.com/libigl/libigl-legacy) with the same SHA1.

I know it's a pain, but I need a working version of *something* so I can start migrating to what's available now.
Also, having a repo that people can download without saying "it's broken" would be nice too.

Just let me know how to build igl::viewer based on the commit SHA's above and I'll be happy. Once again, sorry for being a pain.

**Comment by jdumas** [comment]
The building method hasn't changed much. If you know exactly what commit you were on in 2017 you should be able to get that from the libigl-legacy repo. As for build instructions, you'd have to dig into the CMake code at the time and lookup what CMake options / target names to use. Unless you have a public repo of your project that we can't test I can't help much more than that.

**Comment by Philius** [comment]
`git clone https://git.code.sf.net/p/event-horizon/code event-horizon-code`

**Comment by jdumas** [comment]
Modify your project CMake files as follows (delete `cmake/FindLIBIGL.cmake` and create `cmake/libigl.cmake`):

#### cmake/libigl.cmake

```cmake
if(TARGET igl::core)
    return()
endif()

include(FetchContent)
FetchContent_Declare(
    libigl
    GIT_REPOSITORY https://github.com/libigl/libigl-legacy.git
    GIT_TAG dc9af94b447454ac56179e0d3d53e57a802ad8f1
)

### Available options ###
option(LIBIGL_USE_STATIC_LIBRARY    "Use libigl as static library" OFF)
option(LIBIGL_WITH_ANTTWEAKBAR      "Use AntTweakBar"    OFF)
option(LIBIGL_WITH_CGAL             "Use CGAL"           OFF)
option(LIBIGL_WITH_COMISO           "Use CoMiso"         OFF)
option(LIBIGL_WITH_CORK             "Use Cork"           OFF)
option(LIBIGL_WITH_EMBREE           "Use Embree"         OFF)
option(LIBIGL_WITH_LIM              "Use LIM"            OFF)
option(LIBIGL_WITH_MATLAB           "Use Matlab"         OFF)
option(LIBIGL_WITH_MOSEK            "Use MOSEK"          OFF)
option(LIBIGL_WITH_NANOGUI          "Use Nanogui menu"   ON)
option(LIBIGL_WITH_OPENGL           "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW      "Use GLFW"           ON)
option(LIBIGL_WITH_PNG              "Use PNG"            OFF)
option(LIBIGL_WITH_TETGEN           "Use Tetgen"         OFF)
option(LIBIGL_WITH_TRIANGLE         "Use Triangle"       OFF)
option(LIBIGL_WITH_VIEWER           "Use OpenGL viewer"  ON)
option(LIBIGL_WITH_XML              "Use XML"            OFF)
option(LIBIGL_WITH_PYTHON           "Use Python"         OFF)

message(STATUS "Downloading libigl repository...")
FetchContent_GetProperties(libigl)
if(NOT libigl_POPULATED)
    FetchContent_Populate(libigl)
endif()
list(PREPEND CMAKE_MODULE_PATH "${libigl_SOURCE_DIR}/shared/cmake")
include(${libigl_SOURCE_DIR}/shared/cmake/libigl.cmake)
```

#### CMakeLists.txt

```cmake
cmake_minimum_required(VERSION 3.11)
project(event-horizon-igl)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
include(libigl)

# Add your project files
add_executable(event-horizon-igl event-horizon-igl.cpp)
add_executable(pos-igl pos-igl.cpp)
target_link_libraries(event-horizon-igl PUBLIC igl::core igl::viewer)
target_link_libraries(pos-igl PUBLIC igl::core igl::viewer)
```

**Comment by Philius** [comment]
Done! Thanks for your help, you're in the git commit message and the NEWS file.
