### ISSUE TITLE
Add support for openMP

### ISSUE THREAD

**Issue by jmespadero** [libigl/libigl-example-project#5]
Hi,

Is there any good reason for not having openMP active in the example-project?

I think that just adding this to CMakeLists.txt is enough to check and activate on every 
compiler if openMP is supported and installed. (But I have not tested on visual studio...)

```cmake
find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
endif()
```

**Comment by alecjacobson** [comment]
The main reason is that the built-in clang on mac does not openmp and many
(if not most) of the libigl developers are using this build system.

Instead we have a c++11 version of parallel for (see `igl::parallel_for`)
which works on all build systems and in many cases is competitive with
openMP in terms of performance.

**Comment by jmespadero** [comment]
Thanks for the aclaration.
