### ISSUE TITLE
Unresolved external symbols

### ISSUE THREAD

**Issue by ruoqingsun** [libigl/libigl-example-project#6]
Tools: Windows10 + Visual Studio 2015 + CMake

I have successfully compiled tutorials but when I come to the example project, there are several unresolved external symbols regarding glew. Glew folder has been already included in the dependencies of the project.

![image](https://cloud.githubusercontent.com/assets/4344440/22405332/58462b30-e641-11e6-8da9-5da156811972.png)

![image](https://cloud.githubusercontent.com/assets/4344440/22405339/760c1904-e641-11e6-8b2d-e9ae9a65a335.png)

Your help is appreciated. Thanks.

**Comment by alecjacobson** [comment]
This is a linking issues, so the include paths won't make a difference.

Are you sure that the libigl that this example project is using is up to
date?

**Comment by ruoqingsun** [comment]
Yep. I just downloaded and compiled the tutorials in the libigl today.

**Comment by alecjacobson** [comment]
Thanks for confirming. Could you past the CMAKE output? Specifically I'd
like to see the lines that look like:


libigl includes:
/usr/local/igl/libigl/shared/cmake/../../external/nanogui/ext/eigen;/usr/local/igl/libigl/shared/cmake/../../include;/usr/local/igl/libigl/shared/cmake/../../external/nanogui/ext/glfw/include;/usr/local/igl/libigl/shared/cmake/../../external/nanogui/ext/glfw/include;/usr/local/igl/libigl/shared/cmake/../../external/nanogui/ext/glfw/include
libigl libraries:
libigl extra sources:
libigl extra libraries: /System/Library/Frameworks/OpenGL.framework;glfw
libigl definitions: -DIGL_NO_MOSEK

**Comment by ruoqingsun** [comment]
-- libigl includes:
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/eigen
	 E:/Documents/GitHub/libigl/shared/cmake/../../include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
-- libigl libraries:
-- libigl extra libraries:
	 opengl32
	 glfw
-- libigl definitions:
	 -DIGL_NO_MOSEK
libigl includes: E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/eigen;E:/Documents/GitHub/libigl/shared/cmake/../../include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
libigl libraries: 
libigl extra sources: 
libigl extra libraries: opengl32;glfw
libigl definitions: -DIGL_NO_MOSEK
Configuring done

**Comment by alecjacobson** [comment]
Thanks. Looks like glew is not being appended to the LIBIGL_EXTRA_LIBRARIES
Cmake variable. I believe this is a bug in the
libigl/shared/cmake/CMakeLists.txt file.

I've pushed a potential fix to my dev branch:
https://github.com/libigl/libigl/commit/014faea59457fe9ac17e6ac88164c9d87b40ebfd

I'll merge it to main once the compilation tests pass. In the meantime you
could try it (it's just a changing where one line appears in the file).

**Comment by ruoqingsun** [comment]
It works! Thank you!

**Comment by ruoqingsun** [comment]
I have a question regarding showing the menu with nanogui. When I add LIBIGL_WITH_NANOGUI in CMake, I will get following error: 

Using Win32 for window creation
Using Win32 for window creation
CMake Error at E:/Documents/GitHub/libigl/external/nanogui/ext/glfw/src/CMakeLists.txt:56 (add_library):
  add_library cannot create target "glfw_objects" because another target with
  the same name already exists.  The existing target is created in source
  directory "E:/Documents/GitHub/libigl/external/nanogui/ext/glfw/src".  See
  documentation for policy CMP0002 for more details.


CMake Error at E:/Documents/GitHub/libigl/external/nanogui/ext/glfw/src/CMakeLists.txt:60 (add_library):
  add_library cannot create target "glfw" because another target with the
  same name already exists.  The existing target is a static library created
  in source directory
  "E:/Documents/GitHub/libigl/external/nanogui/ext/glfw/src".  See
  documentation for policy CMP0002 for more details.


-- libigl includes:
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/eigen
	 E:/Documents/GitHub/libigl/shared/cmake/../../include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/nanovg/src
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include
	 E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
-- libigl libraries:
-- libigl extra libraries:
	 opengl32
	 glew
	 glfw
	 nanogui
	 opengl32
-- libigl definitions:
	 -DIGL_NO_MOSEK
	 -DIGL_VIEWER_WITH_NANOGUI
libigl includes: E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/eigen;E:/Documents/GitHub/libigl/shared/cmake/../../include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/nanovg/src;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glfw/include;E:/Documents/GitHub/libigl/shared/cmake/../../external/nanogui/ext/glew/include
libigl libraries: 
libigl extra sources: 
libigl extra libraries: opengl32;glew;glfw;nanogui;opengl32
libigl definitions: -DIGL_NO_MOSEK;-DIGL_VIEWER_WITH_NANOGUI
Configuring incomplete, errors occurred!
See also "E:/Documents/GitHub/libigl-example-project/build/CMakeFiles/CMakeOutput.log".
See also "E:/Documents/GitHub/libigl-example-project/build/CMakeFiles/CMakeError.log".

Otherwise, the program can work smoothly without any menu shown.
![image](https://cloud.githubusercontent.com/assets/4344440/22427524/d9d4b1e0-e703-11e6-9f40-6f9a7009969a.png)

**Comment by alecjacobson** [comment]
Nanogui's cmake is confusing the libigl cmake and glfw is being added twice.

I have not fixed this and might suggest moving all the nanogui stuff to a
truly separate dependency (separate folder from igl/viewer) before sorting
this out.

**Comment by alecjacobson** [comment]
Let's continue this on the main libigl issues page: https://github.com/libigl/libigl/issues/455#issuecomment-276099072
